import type { Product } from './domain';
const v=(id:string,label:string,value:string,priceAdjustment=0)=>({id,label,value,priceAdjustment});
export const sampleProducts:Product[]=[
{id:'prod_krishna',slug:'krishna-idol',name:'Krishna Idol',shortDescription:'A serene, made-to-order Krishna idol personalized for your space.',description:'A thoughtfully crafted decorative idol with your choice of size, colour and optional warm lighting. Each piece is made to order in Bangalore.',category:'Decor',basePrice:699,compareAtPrice:899,active:true,featured:true,stockMode:'made_to_order',leadTime:'4–7 working days',images:[],options:[{id:'opt_ksize',key:'size',name:'Size',type:'radio',required:true,values:[v('ks','Small','small'),v('km','Medium','medium',300),v('kl','Large','large',700)]},{id:'opt_kcolour',key:'colour',name:'Colour',type:'select',required:true,values:[v('kw','Warm White','white'),v('ksd','Sandstone','sandstone'),v('kg','Forest Green','green',100)]},{id:'opt_klight',key:'lighting',name:'Lighting',type:'radio',required:true,values:[v('kln','No','no'),v('kly','Yes','yes',200)]}]},
{id:'prod_nameplate',slug:'custom-name-plate',name:'Custom Name Plate',shortDescription:'A distinctive name plate designed around your home and your story.',description:'Personalize the name, proportions, colour and visual style. We review every design before manufacturing.',category:'Home',basePrice:899,active:true,featured:true,stockMode:'made_to_order',leadTime:'5–8 working days',images:[],options:[{id:'opt_nptext',key:'text',name:'Name / text',type:'text',required:true,placeholder:'e.g. The Sharmas'},{id:'opt_npsize',key:'size',name:'Size',type:'select',required:true,values:[v('np20','20 cm','20cm'),v('np30','30 cm','30cm',400),v('np40','40 cm','40cm',800)]},{id:'opt_npcolour',key:'colour',name:'Colour',type:'select',required:true,values:[v('npb','Black / Gold','black-gold',150),v('npw','White / Oak','white-oak'),v('npg','Forest / Brass','forest-brass',150)]},{id:'opt_npstyle',key:'style',name:'Style',type:'radio',required:true,values:[v('npm','Modern','modern'),v('npc','Classic','classic'),v('npl','Minimal','minimal')]}]},
{id:'prod_gift',slug:'personalized-gift',name:'Personalized Gift',shortDescription:'A small, meaningful object created for one particular person.',description:'Tell us the name, occasion and sentiment. Choose your finish and we will create a thoughtful personalized piece.',category:'Gifts',basePrice:499,active:true,featured:true,stockMode:'made_to_order',leadTime:'3–6 working days',images:[],options:[{id:'opt_gname',key:'name',name:'Name',type:'text',required:true,placeholder:'Name to personalize'},{id:'opt_goccasion',key:'occasion',name:'Occasion',type:'select',required:true,values:[v('gb','Birthday','birthday'),v('ga','Anniversary','anniversary'),v('gh','Housewarming','housewarming'),v('go','Other','other')]},{id:'opt_gcolour',key:'colour',name:'Colour',type:'select',required:true,values:[v('gp','Pearl','pearl'),v('gt','Terracotta','terracotta'),v('gf','Forest','forest')]},{id:'opt_gnote',key:'notes',name:'Personalization notes',type:'textarea',required:false,placeholder:'Tell us what would make it special'}]},
{id:'prod_custom',slug:'custom-3d-print',name:'Custom 3D Print',shortDescription:'Have a sketch, reference or file? Let’s turn it into a made object.',description:'Share the idea, dimensions, quantity and reference files. We will review manufacturability and respond with a transparent quote.',category:'Custom',basePrice:0,active:true,featured:true,stockMode:'quote_only',leadTime:'Quoted after review',images:[],options:[]}
];
export const faqs=[{q:'Can I request a design that is not in the shop?',a:'Yes. Use the Custom Print form to describe your idea and upload reference files privately. We will review it and send a quote.'},{q:'How long does manufacturing take?',a:'Most catalog products take 3–8 working days depending on the design and customization. The product page shows the current estimate.'},{q:'How do I pay?',a:'After your order is safely saved, WhatsApp opens so you can choose UPI or Cash on Delivery when available. An order is not confirmed until we confirm it with you.'},{q:'Can I see a preview before production?',a:'For text-heavy custom products such as name plates, we can share a design preview during WhatsApp confirmation before production begins.'}];
export function getProduct(slug:string){return sampleProducts.find(p=>p.slug===slug)}
