-- Sample development catalog. All prices and copy are editable business data.
INSERT OR IGNORE INTO products (id,slug,name,short_description,description,category,base_price,compare_at_price,active,featured,stock_mode,lead_time,images,created_at,updated_at) VALUES
('prod_krishna','krishna-idol','Krishna Idol','A serene, made-to-order Krishna idol personalized for your space.','A thoughtfully crafted decorative idol with your choice of size, colour and optional warm lighting.','Decor',699,899,1,1,'made_to_order','4–7 working days','[]',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('prod_nameplate','custom-name-plate','Custom Name Plate','A distinctive name plate designed around your home and your story.','Personalize the name, proportions, colour and visual style.','Home',899,NULL,1,1,'made_to_order','5–8 working days','[]',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('prod_gift','personalized-gift','Personalized Gift','A small, meaningful object created for one particular person.','Tell us the name, occasion and sentiment.','Gifts',499,NULL,1,1,'made_to_order','3–6 working days','[]',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('prod_custom','custom-3d-print','Custom 3D Print','Have a sketch, reference or file? Let’s turn it into a made object.','Share the idea, dimensions, quantity and reference files.','Custom',0,NULL,1,1,'quote_only','Quoted after review','[]',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO product_options (id,product_id,name,key,type,required,sort_order,placeholder,created_at,updated_at) VALUES
('opt_ksize','prod_krishna','Size','size','radio',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_kcolour','prod_krishna','Colour','colour','select',1,2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_klight','prod_krishna','Lighting','lighting','radio',1,3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('opt_nptext','prod_nameplate','Name / text','text','text',1,1,'e.g. The Sharmas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_npsize','prod_nameplate','Size','size','select',1,2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_npcolour','prod_nameplate','Colour','colour','select',1,3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_npstyle','prod_nameplate','Style','style','radio',1,4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('opt_gname','prod_gift','Name','name','text',1,1,'Name to personalize',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_goccasion','prod_gift','Occasion','occasion','select',1,2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_gcolour','prod_gift','Colour','colour','select',1,3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('opt_gnote','prod_gift','Personalization notes','notes','textarea',0,4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO product_option_values (id,option_id,label,value,price_adjustment,active,sort_order,created_at,updated_at) VALUES
('ks','opt_ksize','Small','small',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('km','opt_ksize','Medium','medium',300,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('kl','opt_ksize','Large','large',700,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('kw','opt_kcolour','Warm White','white',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('ksd','opt_kcolour','Sandstone','sandstone',0,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('kg','opt_kcolour','Forest Green','green',100,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('kln','opt_klight','No','no',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('kly','opt_klight','Yes','yes',200,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('np20','opt_npsize','20 cm','20cm',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('np30','opt_npsize','30 cm','30cm',400,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('np40','opt_npsize','40 cm','40cm',800,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npb','opt_npcolour','Black / Gold','black-gold',150,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npw','opt_npcolour','White / Oak','white-oak',0,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npg','opt_npcolour','Forest / Brass','forest-brass',150,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npm','opt_npstyle','Modern','modern',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npc','opt_npstyle','Classic','classic',0,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('npl','opt_npstyle','Minimal','minimal',0,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('gb','opt_goccasion','Birthday','birthday',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('ga','opt_goccasion','Anniversary','anniversary',0,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('gh','opt_goccasion','Housewarming','housewarming',0,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('go','opt_goccasion','Other','other',0,1,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('gp','opt_gcolour','Pearl','pearl',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('gt','opt_gcolour','Terracotta','terracotta',0,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('gf','opt_gcolour','Forest','forest',0,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO faqs (id,question,answer,active,sort_order,created_at,updated_at) VALUES
('faq1','Can I request a design that is not in the shop?','Yes. Use the Custom Print form to describe your idea and upload reference files privately.',1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('faq2','How long does manufacturing take?','Most catalog products take 3–8 working days depending on the design and customization.',1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('faq3','How do I pay?','After your order is saved, WhatsApp opens so you can choose UPI or Cash on Delivery when available.',1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO settings (key,value,updated_at) VALUES
('businessName','"MorrowMade"',CURRENT_TIMESTAMP),('whatsappNumber','"919353193080"',CURRENT_TIMESTAMP),('deliveryCharge','100',CURRENT_TIMESTAMP),('freeDeliveryThreshold','1999',CURRENT_TIMESTAMP),('businessCity','"Bangalore"',CURRENT_TIMESTAMP),('aiEnabled','false',CURRENT_TIMESTAMP),('customOrdersEnabled','true',CURRENT_TIMESTAMP),('codEnabled','true',CURRENT_TIMESTAMP),('upiEnabled','true',CURRENT_TIMESTAMP);
PRAGMA optimize;
